[project]
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rattler-build-clobber-bomb-mre"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
reproduce = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml -c conda-forge -c robostack-jazzy" }

[dependencies]
rattler-build = ">=0.35.6"
