name: Pixi CI Workflow

on:
  # on demand
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-with-pixi:
    name: '[pixi:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019]
    steps:
    - uses: actions/checkout@v4

    - name: Print used environment
      shell: bash
      run: |
        env

    - uses: prefix-dev/setup-pixi@v0.8.1


    - name: Reproduce issue
      run: |
        pixi run reproduce
